version: '3'
services:
  app:
    image: kac-api:local
    ports:
      - '8080:8080'
    env_file:
      - .env.${NODE_ENV:-local}
    environment:
      NODE_ENV: local
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
